import { Inter } from "next/font/google";
import NavBar2 from "@/components/NavBar2";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DLEVEL Beta",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gradient-to-t from-[#070941] to-[#08010D] to-78% min-w-[360px]">
          <div className="fixed w-full top-0">
            <div className="relative">
              <NavBar2/>
              <hr className="mx-5 my-1 mb-2 h-[1px] flex bg-white border-0" />
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
